### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by jtyoungo3** [kangarko/ChatControl-Pro#1222]
When I type things such as :) and <3 it does not convert to emoticons. Is there anything I can do to fix this?

**Comment by kangarko** [comment]
Make sure you don't have rules bypass permission (try on a basic account without OP), see our Wikipedia for permissions.

**Comment by jtyoungo3** [comment]
Thank you! This was fixed.

**Comment by cheesepufftyler** [comment]
How do you do this? i just get weird question marks???

**Comment by kangarko** [comment]
https://github.com/kangarko/ChatControl-Pro/wiki/Frequently-Asked-Questions#my-emoticons--are-just-showing-as-

**Comment by cheesepufftyler** [comment]
Still don't work.
1. Instructions suck.
2. For a paid plugin we shouldn't have to go to this trouble for something like this.

**Comment by kangarko** [comment]
This is a problem related to how you are saving the files. You must ensure to follow these instructions and save the file in the proper formatting otherwise the unicode letters will get translated into "?" for most systems.

**Comment by anar4732** [comment]
Change this to LOWEST and BUM FİXED

```
    # Used for checking a message against duplication, time or rules.
   Checker: LOWEST
```
